version: "3"
services:
  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  clientboards-be:
    container_name: clientboards-be-container
    image: python:3.12-slim
    depends_on:
      - redis
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: sh -c "./scripts/setup-app.sh"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - mynetwork

volumes:
  redis_data:

networks:
  mynetwork:
    driver: bridge
