# Generated by Django 5.0.4 on 2024-06-14 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attributes', models.TextField()),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=72)),
                ('country', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('page', 'Page'), ('notiondb', 'Notiondb'), ('divider', 'Divider'), ('todo', 'Todo'), ('olist', 'Olist'), ('ulist', 'Ulist'), ('button', 'Button'), ('header', 'Header'), ('paragraph', 'Paragraph'), ('callout', 'Callout')], max_length=30)),
                ('properties', models.JSONField()),
                ('content', models.TextField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounts')),
                ('parent_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blocks')),
            ],
        ),
        migrations.CreateModel(
            name='BlockPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('additional_conditions', models.JSONField()),
                ('account_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounts')),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blocks')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='api.users'),
        ),
    ]
