# Generated by Django 5.0.4 on 2024-06-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='api.users'),
        ),
    ]
