# Generated by Django 5.0.4 on 2024-04-29 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('page', 'Page'), ('notiondb', 'Notiondb'), ('divider', 'Divider'), ('todo', 'Todo'), ('olist', 'Olist'), ('ulist', 'Ulist'), ('button', 'Button'), ('header', 'Header'), ('paragraph', 'Paragraph'), ('callout', 'Callout')], max_length=30)),
                ('properties', models.JSONField()),
                ('content', models.TextField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounts')),
                ('parent_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blocks')),
            ],
        ),
        migrations.CreateModel(
            name='BlockPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('additional_conditions', models.JSONField()),
                ('account_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounts')),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blocks')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_plan', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=30)),
                ('trial_period', models.IntegerField(default=14)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.accounts')),
            ],
        ),
    ]
