# Generated by Django 5.0.4 on 2024-06-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blocks_account_id_alter_blocks_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocks',
            old_name='account_id',
            new_name='user_id',
        ),
    ]
