# Generated by Django 5.0.4 on 2024-04-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blocks_blockpermissions_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='api.users'),
        ),
    ]
