# Generated by Django 5.0.4 on 2024-07-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_account_id_blocks_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='parent_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.blocks'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='properties',
            field=models.JSONField(blank=True),
        ),
    ]
