# Generated by Django 5.0.4 on 2024-07-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blocks_content_alter_blocks_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='content',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blocks',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.blocks'),
        ),
        migrations.AlterModelTable(
            name='blocks',
            table='blocks',
        ),
    ]
