# Generated by Django 5.0.4 on 2024-07-02 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blocks_content_alter_blocks_parent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockpermissions',
            name='account_id',
        ),
        migrations.AddField(
            model_name='blockpermissions',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='blockpermissions',
            name='permission_type',
            field=models.CharField(choices=[('read', 'READ'), ('write', 'WRITE')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='blockpermissions',
            table='block_permissions',
        ),
    ]
