# Generated by Django 5.0.4 on 2024-07-02 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_blockpermissions_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpermissions',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
