# Generated by Django 5.0.4 on 2024-07-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_blockpermissions_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocks',
            old_name='parent_id',
            new_name='parent_block_id',
        ),
        migrations.AddField(
            model_name='blockpermissions',
            name='owner_id',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockpermissions',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.users'),
        ),
    ]
