# Generated by Django 5.0.4 on 2024-07-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_parent_id_blocks_parent_block_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='id',
            field=models.CharField(max_length=75, primary_key=True, serialize=False),
        ),
    ]
