# Generated by Django 5.0.4 on 2024-07-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_id_blocks_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='type',
            field=models.CharField(choices=[('page', 'PAGE'), ('divider', 'DIVIDER'), ('todo', 'TODO'), ('olist', 'OLIST'), ('ulist', 'ULIST'), ('button', 'BUTTON'), ('header', 'HEADER'), ('paragraph', 'PARAGRAPH'), ('callout', 'CALLOUT'), ('integration_notiondb', 'INTEGRATION_NOTIONDB')], max_length=30),
        ),
    ]
