# Generated by Django 5.0.4 on 2024-07-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_blocks_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('page', 'PAGE'), ('divider', 'DIVIDER'), ('todo', 'TODO'), ('olist', 'OLIST'), ('ulist', 'ULIST'), ('button', 'BUTTON'), ('header', 'HEADER'), ('paragraph', 'PARAGRAPH'), ('callout', 'CALLOUT'), ('integration_notiondb', 'INTEGRATION_NOTIONDB')], max_length=30)),
                ('attributes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'db_table': 'integrations',
            },
        ),
    ]
